# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
  - !type:RoleTimeRequirement
    role: JobWarden
    time: 5h # Goobstation
  - !type:RoleTimeRequirement
    role: JobDetective
    time: 5h # Omustation
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 5h # Omustation
  - !type:RoleTimeRequirement # Omustation
    role: JobBrigmedic
    time: 2h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 30h # Omustation
  #    - !type:SpeciesRequirement # Goob - None Felinid - # Omustation
  #      inverted: true
  #      species:
  #      - Felinid #Omu, add back Felinid
  #  - !type:StyleRequirement
  #    styles:
  #    - HumanHairFloorlengthBedhead
  #    - HumanHairClassicFloorlengthBedhead
  #    - HumanHairFloorlengthBraid
  - !type:OverallPlaytimeRequirement # Omustation
    time: 20h
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  canBeAntag: false
  guides: # goobstation
  - Security
  - SpaceLaw
  - LegalSOP
  - Command
  - HeadOfSecuritySOP
  - SecuritySOP
  - AlertLevels
  - CommandTrainingManual # Omu
  - SecurityTrainingManual # Omu
  goobcoins: 45 #Goob content
  access:
  - Corpsman # Omu
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - External
  - Detective
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: SecurityStaff # goobstation

- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    #gloves: ClothingHandsGlovesCombat - Goobstation, moved to loadouts
    ears: ClothingHeadsetAltSecurity
    #pocket1: OfficerGunCase #Omu, item is in loadout instead
  storage:
    back:
    - Flash
    - MagazinePistol

- type: chameleonOutfit
  id: HeadOfSecurityChameleonOutfit
  job: HeadOfSecurity
  hasMindShield: true
  equipment:
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckCloakHos
