# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 5h # Omustation
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  guides: # goobstation
  - Security
  - LegalSOP
  - OfficerCadetSOP
  - CorporateJudo
  - AlertLevels
  - SecurityTrainingManual # Omu
  goobcoins: 30 #Goob content
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial # goobstation
    components:
      - type: SecurityStaff

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltSecurityRegular # Goobstation
    #pocket1: OfficerGunCase #Omu, item in loadout instead
  storage:
    back:
    - Flash
    #- MagazinePistol # Omu moved to loadouts and will give ammo based on gun

- type: chameleonOutfit
  id: SecurityOfficerChameleonOutfit
  job: SecurityOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretSecurity
    mask: ClothingMaskGasSecurity
    neck: Dinkystar
    gloves: ClothingHandsGlovesColorBlack
