# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 5h
    - !type:RoleTimeRequirement # Goobstation
      role: JobBrigmedic
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 15h #15 hours - Omu edit end: Earn your thankless spot.
#    - !type:SpeciesRequirement # Goob - None Felinid
#      inverted: true
#      species:
#      - Felinid #Omu, add back Felinid
    - !type:OverallPlaytimeRequirement
      time: 10h #10 hours - Omu Edit
  weight: 5
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  guides: # goobstation
  - SpaceLaw
  - LegalSOP
  - Security
  - WardenSOP
  - KravMaga
  - CommandTrainingManual # Omu
  - SecurityTrainingManual # Omu
  goobcoins: 35 #Goob content
  access:
  - Corpsman # Omu
  - Security
  - Brig
  - Armory
  - Maintenance
  - External
  - Detective
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial # goobstation
    components:
      - type: SecurityStaff

- type: startingGear
  id: WardenGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetAltWarden # Goobstation
    # pocket1: OfficerGunCase #Omu, item is in loadout instead
  storage:
    back:
    - Flash
    #- MagazinePistol # Omu moved to loadouts and will give ammo according to weapon
    - ClothingMaskGasSecurity # Goobstation

- type: chameleonOutfit
  id: WardenChameleonOutfit
  job: Warden
  hasMindShield: true
  equipment:
    head: ClothingHeadHatWarden
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterCoatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    neck: Dinkystar
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
