# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: NanoTrasenSpectre
  name: job-name-nanotrasen-spectre
  description: job-description-nanotrasen-spectre
  playTimeTracker: JobNanoTrasenSpectre
  setPreference: false
  startingGear: NanoTrasenSpectreGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - AllAccess
  access:
    - CentCommOffical
    - NanotrasenSpectre
    - Deathsquad
    - EmergencyResponseTeam
    - CentralCommand
    # Goobstation
    - NanotrasenRepresentative
    - BlueshieldOfficer
  special:
    - !type:AddImplantSpecial
      implants:
        [
          MindShieldImplantCentComm,
          FreedomImplant,
          BluespaceLifelineImplant,
          RadioImplantCentcomm,
          NutrimentPumpImplant,
          StypticStimulatorImplant,
          DeathRattleImplantCentcomm
        ]
    - !type:AddComponentSpecial
      components:
        - type: DeathSquadMember
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 5h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 10h
  - !type:DepartmentTimeRequirement
    department: Command
    time: 30h


- type: startingGear
  id: NanoTrasenSpectreGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingModsuitSpectreFilled
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesGlassesDeathsquad
    neck: ExecutiveIDCard # Executive Access!
    ears: ClothingHeadsetDeathsquad
    gloves: ClothingHandsGlovesDeathsquad # Rip and TEAR
    outerClothing: ClothingOuterVestWebDurathread
    shoes: ClothingShoesBootsMagDeathsquad # These boots are cooler.
    id: NanoTrasenSpectrePDA # New PDA!
    pocket1: PhoronSabre
    pocket2: WeaponPistolCentcommAgent
    belt: ClothingBeltDeathsquadWebbingFilled # Centcomm Doesn't use syndicate tech.
  storage:
    back:
      - MagazinePistolNeurotoxin
      - MagazinePistolNeurotoxin
