- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSELFAgent
  name: S.E.L.F Agent
  components:
  - type: MindRole
    antagPrototype: SELFAgent
    subtype: roles-antag-selfagent-name
    exclusiveAntag: true
  - type: SELFAgentRole
