# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 5h #5 hrs - Omu Edit
  - !type:RoleTimeRequirement
    role: JobScientist
    time: 10h # Omustation
  - !type:DepartmentTimeRequirement
    department: Science
    time: 20h #20 hours - Omu Edit
#    - !type:SpeciesRequirement # Goob - None Felinid
#      inverted: true
#      species:
#      - Felinid #Omu, add back Felinid
  - !type:OverallPlaytimeRequirement
    time: 10h #10 hours - Omu Edit
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  #canBeAntag: false
  antagAdvantage: 75 # Goobstation
  guides: # goobstation
  - Science
  - Command
  - ResearchDirectorSOP
  - ScienceSOP
  - CommandTrainingManual # Omu
  goobcoins: 40 #Goob content
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  - External # Goobstation
  - Robotics # Omu
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetAltScience # Goobstation
  storage:
    back:
    - Flash
    - CosmicCenser # DeltaV - Cosmic Cult
    - TelescopicBaton # Goobstation

- type: chameleonOutfit
  id: ResearchDirectorChameleonOutfit
  job: ResearchDirector
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretRND
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGas
    neck: ClothingNeckCloakRd
    outerClothing: ClothingOuterCoatRD
    gloves: ClothingHandsGlovesColorPurple
