# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 0.5h # 30 Minutes # Omu edit start - Play a single shift as passenger first
    #- !type:DepartmentTimeRequirement  # Sometimes you haven't played a department in a while :shrug:
    #  department: Science
    #  time: 36000 #10 hours
    #  inverted: true # Omu edit end
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
  guides: [ Science ] # goobstation
  goobcoins: 20 #Goob content
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ResearchAssistantGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
    pocket2: BookScientistsGuidebook
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ResearchAssistantChameleonOutfit
  job: ResearchAssistant
  equipment:
    head: ClothingHeadHatCardborg
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
